---
title: "Your Title"
subtitle: "BMIN503/EPID600 Final Project"
author: "FirstName LastName"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required. I added a new sentence

## Overview {#sec-overview}

I am working with Dr. Michaela Anderson and Dr. Gabrielle Mezochow - both doctors in Pulmonary Medicine and Critical Care here at Penn. We are working with data from the Lung Transplant Outcomes Group (LTOG), a multi-center cohort study on the long term quality of life and survival of Lung Transplant patients. We are specifically examining the effect of bacterial pathogens on post-Lung Transplantation outcomes.

## Introduction {#sec-introduction}

Infection is the leading cause of morbidity and mortality after lung transplantation, particularly within the first year post-transplant, and remains the highest among all solid organ transplants. (1). Bacterial infections predominate in the first month of transplant, often due to Hospital-acquired and multi-drug resistant organisms. From then on, recurrent infections are often problematic, especially considering the profound presuppression drugs required to prevent organ rejections. (2)

We aim to address the following in this project: what are risk factors associated with infection and infection-related death? What kinds of pathogens are common? Are these infections recurrent? There exists a need for a large resource on microbial data to better under the epidemiology of these infections. This project is interdisciplinary, connecting to the field of biomedical research, informatics, and microbiology. In my experience working in lung transplant research, and certainly in Dr. Anderson’s and Dr. Mezochow’s experience, many unknowns in transplant medicine lead to frustration, hesitation and unease from patients. Our hope is to contribute an incremental amount towards breaking down the barriers to understanding these life-saving surgeries.

Sources so far:

1.  Immunopathology of lung transplantation: from infection to rejection and vice versa - PubMed

2.  Lung Transplantation \| New England Journal of Medicine

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
